apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress-result
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  tls:
  - hosts:
    - result-app.local.test
    secretName: result-app.local.test
  ingressClassName: nginx
  rules:
    - host: result-app.local.test
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: result-service # Cюда вписываем названием СЕРВИСА получить его можно kubectl get svc -n monitoring
              port:
                number: 80