kubectl create secret docker-registry gitlab-regcred \
  --docker-server=registry.gitlab.com \
  --docker-username=deploy-token \
  --docker-password=gldt-cQzkmZz46XTuwF1Qy7Vq \
  --docker-email=registry-deploy@example.com \
  -n develop