rbac:
 enable: true
 rules:
 - resources: ["pods"]
   verbs: ["create","delete","get", "list", "watch"]
 - apiGroups: [""]
   resources: ["pods/attach","pods/exec"]
   verbs: ["get","create","patch","delete"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get","list"]
 - resources: ["secrets"]
   verbs: ["create","get"]
runners:
  image: "alpine:latest"
serviceAccount:
  create: true
  name: gitlab-runner-build
gitlabUrl: "https://gitlab.com/"
runnerToken: glrt-_3dca7iGMF2K6Jb1tDs8lG86MQpwOjE5cGprNAp0OjMKdTpqMWM0aRg.01.1j0ub3t1x
namespace: ci-cd
nodeSelector:
 kubernetes.io/hostname: node02-git
tolerations:
 - key: "ci"
   operator: "Equal"
   effect: "NoSchedule"
   value: "true"
