apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/solodium191/homelab-go.git'
    targetRevision: main
    path: k8s/overlays/develop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true