apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: github-actions-ClusterRoleBinding
subjects:
 - kind: ServiceAccount
   name: github-actions
   namespace: default
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: github-actions-deployer