apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alerting
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "homelab-ca-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - alert.local.test
    secretName: alert-tls
  ingressClassName: nginx
  rules:
  - host: alert.local.test
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
        service:
         name: kube-prometheus-stack-alertmanager
         port:
          number: 9093